# Generated by Django 3.1.3 on 2020-11-24 08:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_auto_20201123_2206'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start', models.TimeField()),
                ('end', models.TimeField()),
                ('title', models.CharField(max_length=255)),
                ('address_street', models.CharField(max_length=255)),
                ('address_city', models.CharField(max_length=100)),
                ('address_country', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('organizer', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='blog',
            name='post_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
