# Generated by Django 3.1.3 on 2020-12-01 15:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0012_eventparticipation'),
    ]

    operations = [
        migrations.AddField(
            model_name='donationsdemo',
            name='country',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='donationsdemo',
            name='donatedVia',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='donationsdemo',
            name='email',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='donationsdemo',
            name='phone',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='donationsdemo',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
